UPDATE USRDBVAH.TB_GUIABI_GUIA SET CD_ESTADO = 'AUTORIZADO', DT_RESPOSTA_CONVENIO = TO_DATE('2016-11-27 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
WHERE DT_GUIA < TO_DATE('2016-11-27 23:59:59', 'YYYY-MM-DD HH24:MI:SS') AND DT_RESPOSTA_CONVENIO IS NULL;

INSERT INTO USRDBVAH.TB_GUIABI_HISTORICO (ID, ID_USER, ID_GUIA, DT_ALTERACAO, CD_ACAO)
  WITH DATA AS
  (
      SELECT
        6                                                       ID_USER,
        ID ID_GUIA,
        TO_DATE('2016-11-27 23:59:59', 'YYYY-MM-DD HH24:MI:SS') DT_ALTERACAO,
        'AUTORIZADO'                                            CD_ACAO
      FROM USRDBVAH.TB_GUIABI_GUIA
      WHERE DT_GUIA < TO_DATE('2016-11-27 23:59:59', 'YYYY-MM-DD HH24:MI:SS') AND DT_RESPOSTA_CONVENIO IS NULL
  )
  SELECT
    USRDBVAH.SEQ_GUIABI_HISTORICO.nextval,
    ID_USER,
    ID_GUIA,
    DT_ALTERACAO,
    CD_ACAO
  FROM DATA;