-- DDL SISTEMA GUIA BI

-- GUIA

CREATE TABLE USRDBVAH.TB_GUIABI_GUIA
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  CD_TIPO VARCHAR2(25),
  CD_SETOR NUMBER(*),
  CD_ATENDIMENTO NUMBER(*),
  DT_SECRETARIA DATE,
  DT_FATURAMENTO DATE,
  DT_AUDITORIA DATE,
  DT_REPOSTA_CONVENIO DATE
);

ALTER TABLE USRDBVAH.TB_GUIABI_GUIA ADD CONSTRAINT FK_GUIABI_GUIA_SETOR FOREIGN KEY (CD_SETOR) REFERENCES DBAMV.TB_SETOR (CD_SETOR);
ALTER TABLE USRDBVAH.TB_GUIABI_GUIA ADD CONSTRAINT FK_GUIABI_GUIA_ANTEDIME FOREIGN KEY (CD_ATENDIMENTO) REFERENCES DBAMV.TB_ATENDIME (CD_ATENDIMENTO);


CREATE SEQUENCE USRDBVAH.SEQ_GUIABI_GUIA;

-- USUÁRIO

CREATE TABLE USRDBVAH.TB_GUIABI_USUARIO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  DS_LOGIN VARCHAR2(255),
  NM_TITULO VARCHAR2(255),
  CD_ROLE VARCHAR2(50)
);

CREATE SEQUENCE USRDBVAH.SEQ_GUIABI_USUARIO;

-- HISTORICO GUIA

CREATE TABLE USRDBVAH.TB_GUIABI_HISTORICO
(
  ID NUMBER(*) PRIMARY KEY NOT NULL,
  ID_USER NUMBER(*),
  ID_GUIA NUMBER(*),
  DT_ALTERACAO DATE
);

ALTER TABLE USRDBVAH.TB_GUIABI_HISTORICO ADD CONSTRAINT FK_GUIABI_HISTORICO_USUARIO FOREIGN KEY (ID_USER) REFERENCES USRDBVAH.TB_GUIABI_USUARIO (ID);
ALTER TABLE USRDBVAH.TB_GUIABI_HISTORICO ADD CONSTRAINT FK_GUIABI_HISTORICO_GUIA FOREIGN KEY (ID_GUIA) REFERENCES USRDBVAH.TB_GUIABI_GUIA (ID);


CREATE SEQUENCE USRDBVAH.SEQ_GUIABI_HISTORICO;